/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ICollider } from "./components/interfaces/ICollider";
import { IAnimation } from "./components/interfaces/IAnimation";
import { ITile } from "./components/interfaces/ITile";
export { ICollider } from "./components/interfaces/ICollider";
export { IAnimation } from "./components/interfaces/IAnimation";
export { ITile } from "./components/interfaces/ITile";
export namespace Components {
    interface ExampleAnimator {
    }
    interface ExampleSprite {
    }
    interface ExampleSpriteMap {
    }
    interface TgCollider {
        "checkCollision": (other: TgCollider) => Promise<ICollider>;
        "checkCollisionOnPosition": (x: number, y: number, width: number, height: number) => Promise<ICollider>;
        "getData": () => Promise<ICollider>;
        "height": number;
        "name": string;
        "offsetX": number;
        "offsetY": number;
        "scale": number;
        "updatePosition": () => Promise<void>;
        "width": number;
        "x": number;
        "y": number;
    }
    /**
     * a component that can be used to display a sprite sheet image in a game or animation scene
     * It takes in the following properties:
     */
    interface TgSprite {
        /**
          * the frame of the sprite image
         */
        "frame": number;
        /**
          * whether to flip the sprite image horizontally
         */
        "hFlip": boolean;
        /**
          * the number of horizontal frames
         */
        "hFrames": number;
        /**
          * the height of the sprite image
         */
        "height": number;
        /**
          * the scale of the sprite image
         */
        "scale": number;
        /**
          * the source of the sprite image
         */
        "src": string;
        /**
          * whether to flip the sprite image vertically
         */
        "vFlip": boolean;
        /**
          * the number of vertical frames
         */
        "vFrames": number;
        /**
          * the width of the sprite image
         */
        "width": number;
    }
    /**
     * Component to animate a tg-sprite component using a animation object
     * It takes in the following properties:
     */
    interface TgSpriteAnimator {
        /**
          * the animations to be played
         */
        "animations": { [key: string]: IAnimation };
        /**
          * the number of times the animation should be played
         */
        "iterationCount": 'infinite' | number;
        /**
          * the animation to play
         */
        "play": string;
        /**
          * trigger if the sprite component hast changed props that used for animation like scale
         */
        "refresh": () => Promise<string>;
        /**
          * the state of the animation
         */
        "state": 'running' | 'paused';
    }
    interface TgSpriteMap {
        "hFrames": number;
        "height": number;
        "scale": number;
        "src": string;
        "tileHeight": number;
        "tileWidth": number;
        "tiles": ITile[];
        "vFrames": number;
        "width": number;
    }
}
export interface TgColliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTgColliderElement;
}
declare global {
    interface HTMLExampleAnimatorElement extends Components.ExampleAnimator, HTMLStencilElement {
    }
    var HTMLExampleAnimatorElement: {
        prototype: HTMLExampleAnimatorElement;
        new (): HTMLExampleAnimatorElement;
    };
    interface HTMLExampleSpriteElement extends Components.ExampleSprite, HTMLStencilElement {
    }
    var HTMLExampleSpriteElement: {
        prototype: HTMLExampleSpriteElement;
        new (): HTMLExampleSpriteElement;
    };
    interface HTMLExampleSpriteMapElement extends Components.ExampleSpriteMap, HTMLStencilElement {
    }
    var HTMLExampleSpriteMapElement: {
        prototype: HTMLExampleSpriteMapElement;
        new (): HTMLExampleSpriteMapElement;
    };
    interface HTMLTgColliderElementEventMap {
        "collision": ICollider;
    }
    interface HTMLTgColliderElement extends Components.TgCollider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTgColliderElementEventMap>(type: K, listener: (this: HTMLTgColliderElement, ev: TgColliderCustomEvent<HTMLTgColliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTgColliderElementEventMap>(type: K, listener: (this: HTMLTgColliderElement, ev: TgColliderCustomEvent<HTMLTgColliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTgColliderElement: {
        prototype: HTMLTgColliderElement;
        new (): HTMLTgColliderElement;
    };
    /**
     * a component that can be used to display a sprite sheet image in a game or animation scene
     * It takes in the following properties:
     */
    interface HTMLTgSpriteElement extends Components.TgSprite, HTMLStencilElement {
    }
    var HTMLTgSpriteElement: {
        prototype: HTMLTgSpriteElement;
        new (): HTMLTgSpriteElement;
    };
    /**
     * Component to animate a tg-sprite component using a animation object
     * It takes in the following properties:
     */
    interface HTMLTgSpriteAnimatorElement extends Components.TgSpriteAnimator, HTMLStencilElement {
    }
    var HTMLTgSpriteAnimatorElement: {
        prototype: HTMLTgSpriteAnimatorElement;
        new (): HTMLTgSpriteAnimatorElement;
    };
    interface HTMLTgSpriteMapElement extends Components.TgSpriteMap, HTMLStencilElement {
    }
    var HTMLTgSpriteMapElement: {
        prototype: HTMLTgSpriteMapElement;
        new (): HTMLTgSpriteMapElement;
    };
    interface HTMLElementTagNameMap {
        "example-animator": HTMLExampleAnimatorElement;
        "example-sprite": HTMLExampleSpriteElement;
        "example-sprite-map": HTMLExampleSpriteMapElement;
        "tg-collider": HTMLTgColliderElement;
        "tg-sprite": HTMLTgSpriteElement;
        "tg-sprite-animator": HTMLTgSpriteAnimatorElement;
        "tg-sprite-map": HTMLTgSpriteMapElement;
    }
}
declare namespace LocalJSX {
    interface ExampleAnimator {
    }
    interface ExampleSprite {
    }
    interface ExampleSpriteMap {
    }
    interface TgCollider {
        "height"?: number;
        "name"?: string;
        "offsetX"?: number;
        "offsetY"?: number;
        "onCollision"?: (event: TgColliderCustomEvent<ICollider>) => void;
        "scale"?: number;
        "width"?: number;
        "x"?: number;
        "y"?: number;
    }
    /**
     * a component that can be used to display a sprite sheet image in a game or animation scene
     * It takes in the following properties:
     */
    interface TgSprite {
        /**
          * the frame of the sprite image
         */
        "frame"?: number;
        /**
          * whether to flip the sprite image horizontally
         */
        "hFlip"?: boolean;
        /**
          * the number of horizontal frames
         */
        "hFrames"?: number;
        /**
          * the height of the sprite image
         */
        "height"?: number;
        /**
          * the scale of the sprite image
         */
        "scale"?: number;
        /**
          * the source of the sprite image
         */
        "src"?: string;
        /**
          * whether to flip the sprite image vertically
         */
        "vFlip"?: boolean;
        /**
          * the number of vertical frames
         */
        "vFrames"?: number;
        /**
          * the width of the sprite image
         */
        "width"?: number;
    }
    /**
     * Component to animate a tg-sprite component using a animation object
     * It takes in the following properties:
     */
    interface TgSpriteAnimator {
        /**
          * the animations to be played
         */
        "animations"?: { [key: string]: IAnimation };
        /**
          * the number of times the animation should be played
         */
        "iterationCount"?: 'infinite' | number;
        /**
          * the animation to play
         */
        "play"?: string;
        /**
          * the state of the animation
         */
        "state"?: 'running' | 'paused';
    }
    interface TgSpriteMap {
        "hFrames"?: number;
        "height"?: number;
        "scale"?: number;
        "src"?: string;
        "tileHeight"?: number;
        "tileWidth"?: number;
        "tiles"?: ITile[];
        "vFrames"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "example-animator": ExampleAnimator;
        "example-sprite": ExampleSprite;
        "example-sprite-map": ExampleSpriteMap;
        "tg-collider": TgCollider;
        "tg-sprite": TgSprite;
        "tg-sprite-animator": TgSpriteAnimator;
        "tg-sprite-map": TgSpriteMap;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "example-animator": LocalJSX.ExampleAnimator & JSXBase.HTMLAttributes<HTMLExampleAnimatorElement>;
            "example-sprite": LocalJSX.ExampleSprite & JSXBase.HTMLAttributes<HTMLExampleSpriteElement>;
            "example-sprite-map": LocalJSX.ExampleSpriteMap & JSXBase.HTMLAttributes<HTMLExampleSpriteMapElement>;
            "tg-collider": LocalJSX.TgCollider & JSXBase.HTMLAttributes<HTMLTgColliderElement>;
            /**
             * a component that can be used to display a sprite sheet image in a game or animation scene
             * It takes in the following properties:
             */
            "tg-sprite": LocalJSX.TgSprite & JSXBase.HTMLAttributes<HTMLTgSpriteElement>;
            /**
             * Component to animate a tg-sprite component using a animation object
             * It takes in the following properties:
             */
            "tg-sprite-animator": LocalJSX.TgSpriteAnimator & JSXBase.HTMLAttributes<HTMLTgSpriteAnimatorElement>;
            "tg-sprite-map": LocalJSX.TgSpriteMap & JSXBase.HTMLAttributes<HTMLTgSpriteMapElement>;
        }
    }
}
