name: Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev libasound2-dev

    - name: Run tests
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      run: npm test

  build-and-release:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: |
        npm run build --prod
        ls -la dist/
        ls -la loader/

    - name: Verify files
      run: |
        echo "Checking dist directory:"
        find dist -type f -not -name "*.map"
        echo "Checking loader directory:"
        find loader -type f -not -name "*.map"

    - name: Get version
      id: get_version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: changelog
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        if [ -z "$LAST_TAG" ]; then
          CHANGES=$(git log --pretty=format:"%s" HEAD)
        else
          CHANGES=$(git log --pretty=format:"%s" $LAST_TAG..HEAD)
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGES" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create release zip
      run: |
        mkdir -p release
        cp -r dist loader release/
        cd release
        zip -r ../tg-engine-v${{ steps.get_version.outputs.version }}.zip .
        cd ..

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        body: |
          ## Changes in this release
          ${{ steps.changelog.outputs.changelog }}
          
          ### Full commit message
          ${{ github.event.head_commit.message }}
        files: |
          tg-engine-v${{ steps.get_version.outputs.version }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
